apiVersion: v1
kind: Namespace
metadata:
  name: leaf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: leaf
  name: greencure-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: greencure
  template:
    metadata:
      labels:
        app.kubernetes.io/name: greencure
    spec:
      containers:
      - name: greencure
        image: aadarshg619/greencure5:latest
        ports:
        - containerPort: 4173
---
apiVersion: v1
kind: Service
metadata:
  namespace: leaf
  name: greencure-svc
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: greencure
